### ISSUE TITLE
Config to disable Forestry backpack module

### ISSUE THREAD

**Issue by Skyqula** [marcin212/Zetta-Industries#19]
And there by remove the dependancy on forestry.

**Comment by Kubuxu** [comment]
Zetta is fully configurable. It has no hard dependencies. There will be just no backpacks if there is no forestry but either way there is also config for it.

**Comment by Skyqula** [comment]
So whats this crash then? http://pastebin.com/bCJzLDRE

**Comment by Kubuxu** [comment]
Sorry it is bug due to unintended behaviour in Forge. @marcin212 is working on fix now. Expect fix in few minutes.

**Comment by marcin212** [comment]
new version: http://www.starchasers.pl:8080/job/Zetta-Industries/92/artifact/build/libs/zettaindustries-1.1-92.jar
