### ISSUE TITLE
Forestry as a dependency crash

### ISSUE THREAD

**Issue by nanakisan** [marcin212/Zetta-Industries#20]
Seems your mod has dependency for Forestry. I would add forestry to remedy this crash. However my modpacks theme would not allow for it.  
  
http://paste.ee/p/mtyqh

**Comment by planetguy32** [comment]
It's been fixed in the build linked at the bottom of #19.

**Comment by nanakisan** [comment]
LOL! pardon my blindness for not seeing the update then xD
carry on

**Comment by marcin212** [comment]
np
