### ISSUE TITLE
Telecommunication connectors

### ISSUE THREAD

**Issue by XFactHD** [marcin212/Zetta-Industries#23]
When updating to ImmersiveEngineering 0.5.3 or higher, trying to connect two telecommunication connectors tells you that the connection is obstructed. This could be caused by the raytracing fix for the HV Relay in IE 0.5.3.

**Comment by magik6k** [comment]
Same here

**Comment by Kubuxu** [comment]
Same here

**Comment by asiekierka** [comment]
Same here

**Comment by cola98765** [comment]
same here

**Comment by skrzyp** [comment]
**sejm tutaj**

![Sejm Tutaj](http://www.wincentyelsner.pl/sites/default/files/imagecache/full-960-700/fot._krzysztof_bialoskorski_22.jpg)

**Comment by RX14** [comment]
Same here!

**Comment by SythsGod** [comment]
Same here

**Comment by ljfa-ag** [comment]
Säjm hier

**Comment by skyem123** [comment]
Same here
###### _asie told me to post this, I'm sorry_.

**Comment by Thog** [comment]
Same here

**Comment by gamemanj** [comment]
Yeah, the same thing occurs on OpenJDK 8... a sec, I'll do an edit to put in the version

**Comment by magik6k** [comment]
Build #97 indeed works for me. (from http://ci.bymarcin.com/job/Zetta-Industries/97/)

**Comment by asiekierka** [comment]
Yeah, works for me too.

**Comment by RX14** [comment]
works for me!

**Comment by Thog** [comment]
Works for me!

**Comment by skyem123** [comment]
Works for me.
##### _asie also made me do this, so sorry..._

**Comment by gamemanj** [comment]
Works here!
And a continuation of previous:

    [gamemanj@archways ~]$ echo "go to #sapphire on EsperNet and RP-murder asie if you don't like it!!!"

**Comment by skrzyp** [comment]
**pracuje dla mnie tutaj**

![pracuje dla mnie tutaj](https://i.imgur.com/tRQbKTA.jpg)

**Comment by lamialily** [comment]
This is the best issue ever. I love you guys <3
