### ISSUE TITLE
squids spawning into acid

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [marcin212/Zetta-Industries#25]
Hello,

squids are spawning in the acid of my battery. Just to let you know :D

**Comment by marcin212** [comment]
Which version are you running?

**Comment by Ganjalf-Amsterdoom** [comment]
I have the version that was on your website, since the website is down/not reachable I have not updated...so i suppose I have an old version.
Are new versions available for downloads?

**Comment by Kubuxu** [comment]
ci.bymarcin.com is new download place.

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you so much! \o/

Could you update the link in the github readme also?

**Comment by Kubuxu** [comment]
Where in readme is link to download?

**Comment by Ganjalf-Amsterdoom** [comment]
Pardon me, I meant in the github wiki, my bad

https://github.com/marcin212/Zetta-Industries/wiki

Your mod is so handy for rf storage(for those who don't use mods like draconic evolution), when I saw the huge battery at btm I was really impressed. Simple and powerful.

By the way I was running v1.1 build 73, just checked.

**Comment by Kubuxu** [comment]
Updated the build site.

Your issue should be for sure resolved in build 97.

**Comment by Ganjalf-Amsterdoom** [comment]
I still have squids in my batteries :D
I take the battery offline, kill the squids, reassemble and after few minutes they spawn in the acid.

Did I understood right that the in/output of energy is from the height of the single battery electrode and that electrodes need the 4 sides facing a full liquid acid source to be 100% efficient?

Thank you for your time.

**Comment by Kubuxu** [comment]
Each side of electrode gives you 2.5kRF/t transfer so by arranging them in different ways they will have different transfer rates.

**Comment by marcin212** [comment]
@Ganjalf-Amsterdoom they still spawn?

**Comment by Ganjalf-Amsterdoom** [comment]
Hello,

apologies for answering so late, I'm using the latest version (build 1.1 105) from couple of hours and it seems to not happen.
Pardon for the late reply.
