### ISSUE TITLE
Telecomunication Cable Connection obstructed

### ISSUE THREAD

**Issue by CaitlynMainer** [marcin212/Zetta-Industries#28]
Build 97 Any connection no matter the distance results in "The connection is obstructed" other cables from IE and II do not have this issue.

**Comment by marcin212** [comment]
Can you send me a screenshot. Which version IE are you running?

**Comment by CaitlynMainer** [comment]
IE is 0.5.4, Forge 1448  http://michi.pc-logix.com/Minecraft_1.7.10_2015-10-16_16-27-54.jpg

**Comment by marcin212** [comment]
Do You have Railcraft?

**Comment by CaitlynMainer** [comment]
Yes, but the invisible blocks are disabled

**Comment by marcin212** [comment]
Can you send me region file?

**Comment by CaitlynMainer** [comment]
I created a new world, tried to place an OC Communication wire, got the same message, Opened the world in MCEdit confirmed there is nothing between the 2 posts.
http://michi.pc-logix.com/New%20World.zip

**Comment by marcin212** [comment]
I have no idea. ![](http://img.bymarcin.com/screenshot-004817-171015.png)

**Comment by marcin212** [comment]
Can You try download my mod again? http://ci.bymarcin.com/job/Zetta-Industries/97/artifact/build/libs/zettaindustries-1.1-97.jar

**Comment by CaitlynMainer** [comment]
The MD5 of all 3 copies of build 97 I have are the same.  I replaced the copy in my pack, and the issue persists.

**Comment by CaitlynMainer** [comment]
It seems this is somehow a conflict between ZI and Immersive Integration, remove II and cables connect properly.

**Comment by CaitlynMainer** [comment]
This randomly seems to work now. No clue why.
