### ISSUE TITLE
OnRightClickCrash

### ISSUE THREAD

**Issue by cpbplus** [marcin212/Zetta-Industries#29]
I spot ghost block placing when i accesing BigBatteryPowerTap
I tried right click it with laser from IC2 and got this:
http://pastebin.com/8UhWSYkq

**Comment by XFactHD** [comment]
@cpbplus are you talking about the mining laser? If that's the case, then the problem might be that the laser is breaking the power tap while the GUI opens and tries to access data from a block that is now null.

**Comment by Kubuxu** [comment]
It is more of a existing issue where GUI is being open on server and not on client or reverse.
