### ISSUE TITLE
Big Reactor Computer Port does not initialize modem after unloading

### ISSUE THREAD

**Issue by iccle** [marcin212/Zetta-Industries#31]
The Big Reactor Computer port will not reinitialize a connected wired modem after the chunk is unloaded and the player later returns. 

The modem appears to be visually connected but is not and needs toggled to function

**Comment by marcin212** [comment]
Open Computer or ComputerCraft?

**Comment by iccle** [comment]
ComputerCraft, CraftOS 1.7
MCP: v9.05
FML v7.10.99.99
Minecraft Forge 10.13.4.1492
(Tekkit Legends mod pack)

**Comment by marcin212** [comment]
It is only Open Computer port. Look at #32
