### ISSUE TITLE
Crash on server startup TileentitySpecialRenderer

### ISSUE THREAD

**Issue by IBlackI** [marcin212/Zetta-Industries#42]
http://pastebin.com/dJuCQ9Pm

Whenever I try and start up a server it crashes, when I delete ZI it works. Forge: 7.99.40.1614

Mods:
Aroma1997Core-1.7.10-1.0.2.16
  AromaBackup-1.7.10-0.1.0.0
  BiblioCraft[v1.11.4][MC1.7.10]
  BiblioWoods[Forestry][v1.7]
  buildcraft-7.1.16
  buildcraft-compat-7.1.3
  Carpenter's Blocks v3.3.7 - MC 1.7.10
  Chisel-2.9.5.11
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.1.2-325
  compactmachines-1.7.10-1.21
  EnderStorage-1.7.10-1.4.7.37-universal
  extrautilities-1.2.12
  Flans Mod-1.7.10-4.10.0
  forestry_1.7.10-4.2.11.59
  FTBLib-1.7.10-1.0.18.3
  FTBUtilities-1.7.10-1.0.18.3
  ImmersiveEngineering-0.7.5
  immersiveintegration-0.6.8
  industrialcraft-2-2.2.821-experimental
  Jabba-1.2.1a_1.7.10
  logisticspipes-0.9.3.114
  Mantle-1.7.10-0.3.2b
  MineFactoryReloaded-[1.7.10]2.8.1-174
  MineTweakerRecipeMaker-1.7.10-1.1.0.11
  neiaddons-1.12.14.40-mc1.7.10
  NEIIntegration-MC1.7.10-1.1.2
  NotEnoughItems-1.7.10-1.0.5.118-universal
  OpenBlocks-1.7.10-1.5.1
  OpenComputers-MC1.7.10-1.6.0.3-rc.1-universal
  OpenModsLib-1.7.10-0.9.1
  OpenPeripheralAddons-1.7.10-0.5.1
  OpenPeripheralCore-1.7.10-1.3
  OpenPeripheralIntegration-1.7.10-0.5
  OpenPrinter-MC1.7.10-0.1.0.132
  OpenSecurity-1.7.10-1.0-91
  1.7.10-Pistronics2-v0.6.4
  ProjectRed-1.7.10-4.7.0pre12.95-Compat
  ProjectRed-1.7.10-4.7.0pre12.95-Base
  ProjectRed-1.7.10-4.7.0pre12.95-Mechanical
  ProjectRed-1.7.10-4.7.0pre12.95-World
  ProjectRed-1.7.10-4.7.0pre12.95-Lighting
  ProjectRed-1.7.10-4.7.0pre12.95-Integration
  Railcraft_1.7.10-9.10.0.0
  RTG-1.7.10-0.7.0
  Thaumcraft-1.7.10-4.2.3.5
  thaumcraftneiplugin-1.7.10-1.7a
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.1.2-240
  ThermalFoundation-[1.7.10]1.2.3-112
  TConstruct-1.7.10-1.8.8
  TMechworks-1.7.10-0.2.15.106
  WR-CBE-1.7.10-1.4.1.9-universal
  zettaindustries-1.1-119
  Ztones-1.7.10-2.2.1

**Comment by marcin212** [comment]
Can you upload all startup logs?

**Comment by IBlackI** [comment]
https://paste.ee/p/2GkRJ

**Comment by IBlackI** [comment]
Do you need anything else? Hope you can fix it soon :-)
