### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rcistano** [marcin212/Zetta-Industries#43]
Any plans for 1.8.9?

**Comment by marcin212** [comment]
I have plans for 1.9.

**Comment by border999** [comment]
what about 1.10.2?

**Comment by marcin212** [comment]
https://img.bymarcin.com/screenshot-2016-07-27_03-54-44.png

**Comment by marcin212** [comment]
new beta version on jenkins: https://ci.bymarcin.com/
