### ISSUE TITLE
Crash when breaking telecommunications connector

### ISSUE THREAD

**Issue by cloakable** [marcin212/Zetta-Industries#44]
[crash-2016-07-18_20.33.29-server.txt](https://github.com/marcin212/Zetta-Industries/files/370088/crash-2016-07-18_20.33.29-server.txt)

**Comment by marcin212** [comment]
Check new version: https://ci.bymarcin.com/job/Zetta-Industries/lastSuccessfulBuild/artifact/build/libs/zettaindustries-1.1-120.jar

**Comment by cloakable** [comment]
http://paste.ee/p/yoxGu crash on startup with new version.

Also, 1.1-120 isn't linked to on https://zi.bymarcin.com/ ; might want to check that

**Comment by marcin212** [comment]
1.1-120 isn't linked to on https://zi.bymarcin.com/ , because required OpenComputers 1.6.  I will try to fix it tomorrow.

**Comment by marcin212** [comment]
Could you try new version: https://cloud.bymarcin.com/index.php/s/0VnHKDYCqGD6v21 ?(Create backup first.)
