### ISSUE TITLE
Charcoal blocks from AA are unable to be smelted into graphite blocks

### ISSUE THREAD

**Issue by topher2010** [marcin212/Zetta-Industries#46]
We are using Zetta Industries 1.10-126, and noticed the charcoal blocks from Actually Additions won't smelt into graphite blocks.

**Comment by Kubuxu** [comment]
Only Charcoal Blocks for ZI smelt into graphite.

**Comment by demethan** [comment]
work around. if you use the forestry worktable you can choose the crafting output.
