### ISSUE TITLE
crash when place a RF Meter

### ISSUE THREAD

**Issue by Cassiobsk8** [marcin212/Zetta-Industries#49]
game crash after place rf meter, when reload the rf meter is a white box without texture and crash again if i look direct at him

http://pastebin.com/PvWiTqaC

**Comment by marcin212** [comment]
Probably something changed in OC. If you don't use OC to read the meter, you can turn off the integration in the ZI config.

**Comment by Cassiobsk8** [comment]
Yes, put oc.methods.allowed to false solves the problem thanks
