### ISSUE TITLE
OC Wire crashing

### ISSUE THREAD

**Issue by CaitlynMainer** [marcin212/Zetta-Industries#5]
Keep having issue with the OC wire crashing or hanging the server the latest crash was: http://paste.pc-logix.com/view/4b1f7c64  Running ZI build 67, IE 0.3.3, and OC 1.5.13.28
Latest freeze was roughly 100,000 lines of this http://paste.pc-logix.com/view/3f4eb249
 in the log, the GC hung and the server locked.  Should note this is an 8 core box, and 7 GB is dedicated to MC.

**Comment by marcin212** [comment]
Test the newest version. If it still crashes, give me your world save.

http://www.starchasers.pl:8080/job/Zetta-Industries/68/artifact/build/libs/zettaindustries-1.1-68.jar

**Comment by CaitlynMainer** [comment]
Tossed it on my server, will report any issues, thanks!

**Comment by CaitlynMainer** [comment]
Hung the server again, another 100k lines of http://paste.pc-logix.com/view/cd233ec0
 before the GC died and ran out of RAM

**Comment by marcin212** [comment]
@CaitlynMainer Can you send me world save or screen?

**Comment by marcin212** [comment]
Probably fixed:
http://www.starchasers.pl:8080/job/Zetta-Industries/lastSuccessfulBuild/artifact/build/libs/zettaindustries-1.1-70.jar

**Comment by CaitlynMainer** [comment]
Sorry I posted this issue and fell asleep.  If this build doesn't fix it I'll tar up the world directory, warning though it will be largish

**Comment by CaitlynMainer** [comment]
Sorry meant to reply and let you know that this seems fixed.  Thanks!
