### ISSUE TITLE
[1.12] ZI crashes with ComputerCraft

### ISSUE THREAD

**Issue by KajesLorian** [marcin212/Zetta-Industries#56]
Crashes on startup.

https://pastebin.com/NCmiRZSL

zettaindustries-1.3-1.12.1-143
ComputerCraft1.80pr1
Minecraft Version 1.12.1

**Comment by KajesLorian** [comment]
Off topic, but can someone delete my fork I accidentally made, or walk me through doing it myself? Misclicked.

**Comment by marcin212** [comment]
@KajesLorian your fork->settings->Danger Zone->Delete this repository

**Comment by marcin212** [comment]
Should be fixed in zettaindustries-1.3-1.12.1-144
