### ISSUE TITLE
A small JEI issue

### ISSUE THREAD

**Issue by TheLimePixel** [marcin212/Zetta-Industries#57]
Whenever you check the uses of any item in JEI, this is one of the pages you get:
![image](https://user-images.githubusercontent.com/25333164/30772670-7ef1de9e-a060-11e7-9fa5-4bd0789bfaf9.png)

 It's just annoying as it isn't an item-specific use.

**Comment by marcin212** [comment]
Fixed in zettaindustries-1.3-1.12.2-153
