### ISSUE TITLE
Note on newer OC dev versions

### ISSUE THREAD

**Issue by brisingraerowing** [marcin212/Zetta-Industries#59]
OC has changed the wireless card to have 2 tiers (the current one is tier 2 and there is a new, limited tier 1 card). This also means that the item names have changed (from wlancard to wlancard1 and wlancard2), breaking a few mods (ZI being one of them).

I can fix and build this myself easily enough (I am using dev OC versions due to fixes for some bugs I was having trouble with), but I thought I'd let you know about the change.

**Comment by marcin212** [comment]
Thanks for the report!
