### ISSUE TITLE
OC Connector Not Showing Up

### ISSUE THREAD

**Issue by Sixdd6** [marcin212/Zetta-Industries#60]
I am looking in the creative screen and don't see the connector for OC cables anywhere, the cable shows but no connector. I checked in JEI as well and same result even when searching with @zetta.

zettaindustries-1.3-1.12.2-145.jar
forge 1.12.2 - 14.23.1.2590

**Comment by alucard87pl** [comment]
@Sixdd6 Do you have Immersive Engineering in your modpack? It's required to have Zetta's connectors.

**Comment by Sixdd6** [comment]
Yeah latest IE for 1.12.2

**Comment by metoray** [comment]
I have the same issue, I'd also like to add that the cable items create LV wire when used with the LV wire connector.

**Comment by marcin212** [comment]
fixed in zettaindustries-1.3-1.12.2-148
