### ISSUE TITLE
Sneaking right click on power tap doesn't switch it.

### ISSUE THREAD

**Issue by abdullamu** [marcin212/Zetta-Industries#67]
As the title says I build big battery and when its formed I try to switch the power tap but it doesn't switch.

**Comment by calloatti** [comment]
Use your empty hand.

**Comment by abdullamu** [comment]
I did , strange enough I started new world and it works fine,
But when I return to my world it doesn't work.

**Comment by abdullamu** [comment]
Aha found the problem.
In my offhand I had calculator and taking it off made it works fine.
