### ISSUE TITLE
[1.12] Unable to control Big battery using CC

### ISSUE THREAD

**Issue by ilhamfu** [marcin212/Zetta-Industries#71]
I've been playing with zetta industries and computercraft along with some other mod. I've build simple big battery, unfortunately i can't control it using computercraft, either by connecting it using modem or direct connect. 
Using the latest version of ZI and CC

**Comment by ProsperCraft** [comment]
We are having problems with the opencomputers using the port as well.

And if you use a tap, it can only see the 2 gig that the tap makes available not entire capacity.
