### ISSUE TITLE
Language file keys don't include mod id, causing conflicts with Modular Machinery

### ISSUE THREAD

**Issue by 3TUSK** [marcin212/Zetta-Industries#77]
### Synopsis
`tile.blockcontroller.name=Super Conductor Controller` has conflict with [`tile.blockcontroller.name=Machine Controller` from Modular Machinery](https://github.com/HellFirePvP/ModularMachinery/blob/be403ec4b42fe076af4b923ae2b5c9e478e03200/src/main/resources/assets/modularmachinery/lang/en_US.lang#L93). This leads to confusing tooltips when mods like The One Probe is used, and both mods in question are installed.

### Environment

* Modular Machinery 1.12-1.9.4
* Zetta Industries 1.3-1.12.2-155

### Analysis
Mod id should be part of language entry key. See also elytra/BetterBoilers#5, jaquadro/StorageDrawers#611.

### Final thought
With incoming Minecraft 1.13 changes of enforcing namespace in language keys of blocks & items, doing so earlier may make the future transition more smooth. Please consider.

**Comment by 3TUSK** [comment]
Addendum: see also HellFirePvP/ModularMachinery#94.

**Comment by marcin212** [comment]
fixed
