### ISSUE TITLE
java.lang.NoClassDefFoundError: com/bymarcin/zettaindustries/mods/ocwires/item/ItemTelecommunicationWire

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [marcin212/Zetta-Industries#8]
Hello,

the game crash on startup with:

java.lang.NoClassDefFoundError: com/bymarcin/zettaindustries/mods/ocwires/item/ItemTelecommunicationWire

Am I missing something?

Thank you for your time.

**Comment by marcin212** [comment]
Update zettaindustries or Immersive Engineering.

**Comment by Ganjalf-Amsterdoom** [comment]
Updating Imm.Eng. did the trick, thank you for your time.
