### ISSUE TITLE
OC integration for big_battery missing methods?

### ISSUE THREAD

**Issue by Garagoth** [marcin212/Zetta-Industries#81]
Hi.

Connecting big battery via computer port to OC network makes component "big_battery" visible,
but it has no methods, just address and type.
RFMeter shows some methods, so I guess that is fine

Zetta Industries 1.3-1.12.2-158
OpenComputers 1.7.2-67
Forge 14.23.5.2772

**Comment by marcin212** [comment]
@Garagoth Could you try this version: https://ci.starchasers.ovh/jenkins/job/Zetta-Industries/lastSuccessfulBuild/artifact/build/libs/zettaindustries-1.3-1.12.2-159.jar ?

**Comment by Garagoth** [comment]
Hi.

Now I can see some functions, however:
- None have any doc (rfmeter has at least method signatures so you can work out meaning from parameter names)
- setIn() / setOut() erases power tap label so you cannot use this function twice without entering label manually again

Other methods seem to work fine...

Regards,
Garagoth.

**Comment by marcin212** [comment]
Fixed
