### ISSUE TITLE
Can't shift click battery power tap in Tekkit 2 (problem is totem in offhand)

### ISSUE THREAD

**Issue by lorenzomartin12** [marcin212/Zetta-Industries#93]
When I went to shift right click my battery power tap in my main hardcore Tekkit 2 world, it didn't change from positive to negative. When I switched to my creative test world, it worked no problem. I also made a separate hardcore world, switched to creative to spawn in the power tap, and switched back to survival and the power tap also worked without any problems. In a last ditch effort I nuked my base in a backup to make sure nothing I built was the problem and of course that didn't work. I'm on version 1.2.1. Anyone experience this problem or have any ideas of why its happening? Edit: So I guess having a totem in your offhand is the bug. That was anticlimactic.

**Comment by xJon** [comment]
As this was caused by having an item in the offhand this can probably be closed.
